/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 gun.glb 
Author: PoketCoco (https://sketchfab.com/PoketCoco)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gun-6475db58c91345b09db7ca95986a8922
Title: Gun
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Gun(props) {
  const { nodes, materials } = useGLTF('/models/gun.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.aiStandardSurface1SG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.aiStandardSurface2SG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.aiStandardSurface2SG} />
      </group>
    </group>
  )
}
export default Gun;
useGLTF.preload('/models/gun.glb')
